### PR TITLE
Jade template and pagination support

### PR DESCRIPTION
**Pull request by thegreatape**
I wanted to write my blog's skin templates in Jade, so I've added support for using languages aside from haml.  The template engine still defaults to haml- if one wants to use Jade instead, you pass in the engine as a config parameter:
      require('wheat')(__dirname, {templateEngine: 'jade'})
 These changes should make it bit easier if someone else wants to add ejs, handlebars, or whatever.

I also wanted to be able to paginate articles, so index now takes an additional page parameter. It's up to the author's template to build next, previous, etc links.

Everything here is backward-compatible.  Or it should be at any rate- I was able to run the howtonode.org repo without any problems that I could see.

### CODE REVIEW

**Comment by jeromegn** [comment]
+1 I pulled and built the package manually and it works well.

**Comment by itwars** [comment]
I'm divin into wheat, it's full of features, expect the pagination ! I agree with you  thegreatape / WE ALL NEED PAGINATE to make it work with haml too !

**Comment by RusAlex** [comment]
will this pull request add to a wheat repo by author ?

**Comment by damienklinnert** [comment]
+1 plz merge

**Comment by thegreatape** [comment]
(closing to clean up my own open PR list)

**Pull request closed without merging**
